{% set name = "doubtlab" %}
{% set version = "0.2.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ab23fc36548a970fe52caea26c8c626a0d30bad78b44889e208f7dad455e7642

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4.0
    - cleanlab >=2.0
    - pandas >=1.3.3
    - scikit-learn >=1.0.0

test:
  imports:
    - doubtlab
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://koaning.github.io/doubtlab/
  summary: Don't Blindly Trust Your Labels
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    This repository contains general tricks that may help you find bad, 
    or noisy, labels in your dataset. The hope is that this repository 
    makes it easier for folks to quickly check their own datasets before 
    they invest too much time and compute on gridsearch.

    PyPI: [https://pypi.org/project/doubtlab/](https://pypi.org/project/doubtlab/)

  doc_url: https://koaning.github.io/doubtlab/
  dev_url: https://github.com/koaning/doubtlab

extra:
  recipe-maintainers:
    - sugatoray
    # maintainer(s) from upstream repo
    - koaning
